services:
  - type: web
    name: deutschlehrer-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    
  - type: pserv
    name: deutschlehrer-db
    env: postgresql
    plan: free
    ipAllowList: []
